addSbtPlugin("ch.epfl.scala" % "sbt-scalafix"   % "0.9.27")
addSbtPlugin("com.geirsson"  % "sbt-ci-release" % "1.5.7")
addSbtPlugin("org.scalameta" % "sbt-scalafmt"   % "2.4.2")
addSbtPlugin("org.scoverage" % "sbt-scoverage"  % "1.6.1")
addSbtPlugin("org.scoverage" % "sbt-coveralls"  % "1.2.7")
addSbtPlugin("ch.epfl.scala" % "sbt-bloop"      % "1.4.8")
addSbtPlugin("com.eed3si9n"  % "sbt-buildinfo"  % "0.10.0")
addSbtPlugin("org.scalameta" % "sbt-mdoc"       % "2.2.18")
