addSbtPlugin("ch.epfl.scala" % "sbt-scalafix"        % "0.9.11")
addSbtPlugin("com.geirsson"  % "sbt-ci-release"      % "1.4.31")
addSbtPlugin("org.scalameta" % "sbt-scalafmt"        % "2.0.6")
addSbtPlugin("org.scoverage" % "sbt-scoverage"       % "1.6.0")
addSbtPlugin("com.codacy"    % "sbt-codacy-coverage" % "3.0.2")
addSbtPlugin("ch.epfl.scala" % "sbt-bloop"           % "1.3.4")
